name: todo_list
description: A simple Flutter To-Do List app with SQLite, notifications, and GetX.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.27.0
  firebase_auth: ^4.17.0

  # Core
  cupertino_icons: ^1.0.8
  get: ^4.6.6

  # SQLite
  sqflite: ^2.3.2
  path: ^1.9.0
  path_provider: ^2.1.2

  # Notifications
  flutter_local_notifications: ^17.0.0
  timezone: ^0.9.2
  cloud_firestore: ^4.15.0
  

  # UI & Formatting
  google_fonts: ^6.2.0
  flutter_svg: ^2.0.9
  intl: ^0.18.1

  # Optional persistence (e.g., dark mode, auth session)
  shared_preferences: ^2.2.2
  oktoast: ^3.3.1


  table_calendar: ^3.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
